// Fast Engine Graphical User Interface (F.E.G.U.I)
// This feature is a part of FastEngine
// by Mario Freire
// Copyright (C) 2012 DSP Interactive. All rights reserved.
// Development Systems and Programs
// See more information in the website: https://www.dspinteractive.com.br

#ifndef CTYPES_H
#define CTYPES_H



/**************************
 * Includes
 *
 **************************/

#define GLUT_DISABLE_ATEXIT_HACK

#include <windows.h>
#include <windef.h>
#include <math.h>
#include <set>
#include <string>
#include <stdio.h>
#include <stdlib.h>
#include <io.h>
#include <gl/gl.h>
#include <gl/glu.h>
#include <gl/glut.h>
#include <gl/glaux.h>
#include <time.h>

typedef COLORREF TColor;

#pragma option push -b-
enum TAlign { alNone, alTop, alBottom, alLeft, alRight, alClient, alCustom };
#pragma option pop

#pragma option push -b-
enum TFormBorderStyle { bsNone, bsSingle, bsSizeable, bsDialog, bsToolWindow, bsSizeToolWin };
#pragma option pop

typedef TFormBorderStyle TBorderStyle;

#pragma option push -b-
enum TBevelStyle { bvLowered, bvNone, bvRaised, bvSpace };
#pragma option pop

#pragma option push -b-
enum TAlignment { taLeftJustify, taRightJustify, taCenter };
#pragma option pop

typedef TAlignment TLeftRight;

#pragma option push -b-
enum TEditCharCase { ecNormal, ecUpperCase, ecLowerCase };
#pragma option pop

typedef struct bmp
{
 BITMAPFILEHEADER	head;
 BITMAPINFO		info;
 void*			data;
 int			width;
 int			height;
 int			size;
 unsigned char*		bgr;
}BMP;


// Full class list

class TShape;
class TPanel;
class TBevel;
class TGroupBox;
class TScrollBar;
class TCheckBox;
class TRadioButton;
class TTextBox;
class TListBox;
class TListScrollBar;
class TComboBox;
class TComboBoxEdit;
class TComboListBox;
class TLabel;
class TEdit;
class TSpeedButton;
class TGlyphButton;
class TButton;
class TComponent;
class TControl;
class TWinControl;
class TWindow;
class TMenu;
class TMenuItems;
class TMenuItem;
class TMainMenu;
class TToolBar;
class TToolButton;
class TProgressBar;
class TTransparentBox;
class TTimer;
class TViewport;
class TImageList;
class TDockBar;
class TTrackBar;
class TUpDown;
class TVideoPlayer;
class TListView;
class TTreeView;
class THeaderBar;
class TComboBoxEx;
class TRichEdit;
class TColorBox;
class TColorBar;
class TColorListBox;
class TColorComboBox;
class TCategoryBox;
class TGridPanel;
class TFlowPanel;
class TMultiPanel;
class TSplitter;
class TDivider;
class TSeparator;
class TMultiViewport;
class TScrollBox;
class TDrawGrid;
class TStringGrid;
class TControlBar;
class TCoolBar;
class TSpinEdit;
class TPie;
class TLine;
class TGradient;
class TPerformanceDisplay;
class TPerformanceBox;
class TPerformanceMeter;
class TVUMeter;
class TShellImageList;
class TShellListView;
class TShellTreeView;
class TShellComboBox;
class TShellCategoryBox;
class TShellLinksBox;
class TShellBox;
class TCommonDialog;
class TOpenDialog;
class TSaveDialog;
class TColorDialog;
class TFontDialog;
class TSearchDialog;
class TReplaceDialog;
class TBrowseDialog;
class TPrintDialog;
class TPrintSetupDialog;
class TComputerDialog;
class TSoundDialog;
class TInternetOptionsDialog;
class TNetworkDialog;
class TServiceDialog;
class TFormDialog;
class TCustomDialog;
class TFrame;
class TFrameSet;
class TFrameBox;
class TTcpServer;
class TUdpServer;
class TTcpClient;
class TUdpClient;
class TSynEdit;
class TShellEdit;
class TConsoleBox;
class TTerminalBox;
class TViewportBox;
class TFourViewportBox;
class TFourViewport;
class TThreeViewport;
class TThreeViewportBox;
class TMultiViewportBox;
class TWidget;
class TCommonWidget;
class TFormWidget;
class TWindowWidget;
class TChildWidget;
class TMainWidget;
class TDockWidget;
class TDialogWidget;
class TViewportWidget;
class TMainWindow;
class TRootWindow;
class TRootWidget;
class TDesktopWindow;
class TDesktopWidget;
class TBackgroundWidget;
class TSynWidget;
class TSynWindow;
class TRender;
class TRenderBox;
class TRender3D;
class TScrollSphere;
class TSpinSphere;
class TArrowButton;
class TArrowShape;
class TScrollEdit;
class TTrackEdit;
class TTrackUpDown;
class TRadialGradient;
class TLinearGradient;
class TConeGradient;
class TGradientFill;
class TGradientLine;
class TBlur;
class TBlurBox;
class TMotionBlur;
class TMotionBlurBox;
class TDirectionBlur;
class TDirectionBlurBox;
class TGaussianBlur;
class TGaussianBlurBox;
class TSmoothBlur;
class TSmoothBlurBox;
class TSmoothBox;
class TRoundedBox;
class TBrush;
class TPen;
class TCanvas;
class TCanvasBox;
class TImage;
class TPaintBox;
class TThread;
class TThreadComponent;
class TThreadManager;
class TApplication;
class TApplicationEvents;
class TNormalize;
class TNormal;
class TVector;
class TVector2D;
class TVector3D;
class TVector4D;
class TVectorBar;
class TVectorBox;
class TCoord;
class TTexture;
class TTextureCoord;
class TTextureImage;
class TTextureImageList;
class TTextureManager;
class TTextureManager;
class TTextureBar;
class TTextureBox;
class TModel;
class TModelBox;
class TModelBar;
class TModelView;
class TModelViewport;
class TModelToolBar;
class TTextureToolBar;
class TSector;
class TSectorBox;
class TSpeedSet;
class TSpeedBox;
class TSpeedBar;
class TSpeedNavigator;
class TDataSet;
class TDBConnection;
class TTable;
class TQuery;
class TDBNavigator;
class TStoreProc;
class TStoreVar;
class TStoreFunc;
class TStoreBox;
class TAnimate;
class TMediaPlayer;
class TAudioPlayer;
class TVideoPlayer;
class TVideo;
class TMimeListView;
class TFileTypesListView;
class TFileComponent;
class TFile;
class TFileSystem;
class TAction;
class TActionManager;
class TActionToolBar;
class TMenuToolBar;
class TMainToolBar;
class TAdvToolBar;
class TStatusBar;
class TSnapGrip;
class TMotionBox;
class TNotebook;
class TPageControl;
class TTabControl;
class TTabSet;
class TDockSet;
class TPageSet;
class TFilterComboBox;
class TFileComboBox;
class TDriveComboBox;
class TFileListBox;
class TDirectoryListBox;
class TFilter;
class TBehaviorManager;
class TAIManager;
class TAI;
class TSynAI;
class TSimAI;
class TSynMotion;
class TSimMotion;
class TShoot;
class TShooter;
class TGun;
class TGunBar;
class TGunBox;
class TGunView;
class TArmor;
class TArmorWidget;
class TAmmo;
class TAmmoWidget;
class THealth;
class THealthBar;
class THealthBox;
class THealthView;
class THealthWidget;
class THEV;
class THEVBar;
class THEVBox;
class THEVWidget;
class THEVView;
class TInventory;
class TInventoryBar;
class TInventoryBox;
class TInventoryView;
class TInventoryWidget;
class TTroop;
class TTroopBar;
class TTroopBox;
class TTroopView;
class TTroopWidget;
class TSquad;
class TSquadBar;
class TSquadBox;
class TSquadView;
class TSquadWidget;
class TExpression;
class TExpressionBar;
class TExpressionBox;
class TExpressionView;
class TExpressionWidget;
class TExpressionEvaluation;
class TExpressionEvaluationBar;
class TExpressionEvaluationBox;
class TExpressionEvaluationView;
class TExpressionEvaluationWidget;
class TThinkGen;
class TThinkGenManager;
class TThinkManager;
class TThinkGenBar;
class TThinkGenBox;
class TThinkGenView;
class TThinkGenWidget;
class TThinkGenDialog;
class TThinkGenPropertiesDialog;
class TSim;
class TSyn;
class TDyn;
class TGen;
class TDirect;
class TReal;
class TDynManager;
class TDynamicManager;
class TDynamicBar;
class TDynamicBox;
class TDynamicView;
class TDynamicWidget;
class TDynamicDialog;
class TDynamicsManager;
class TDynamicsDialog;
class TArmorDialog;
class TAmmoDialog;
class TAppearance;
class TAppearanceBar;
class TAppearanceBox;
class TAppearanceView;
class TAppearanceWidget;
class TAppearanceDialog;
class TAppearanceManager;
class TEffects;
class TEffectsBar;
class TEffectsBox;
class TEffectsView;
class TEffectsWidget;
class TEffectsDialog;
class TEffectsManager;
class TSpecialEffects;
class TSpecialEffectsBar;
class TSpecialEffectsBox;
class TSpecialEffectsView;
class TSpecialEffectsWidget;
class TSpecialEffectsDialog;
class TSpecialEffectsManager;
class TFXEffects;
class TFXEffectsBar;
class TFXEffectsBox;
class TFXEffectsView;
class TFXEffectsWidget;
class TFXEffectsDialog;
class TFXEffectsManager;
class TInvite;
class TInviteBar;
class TInviteBox;
class TInviteView;
class TInviteWidget;
class TInviteDialog;
class TInviteManager;
class TUser;
class TUserBar;
class TUserBox;
class TUserView;
class TUserWidget;
class TUserDialog;
class TUserManager;
class TLogin;
class TLoginBar;
class TLoginBox;
class TLoginView;
class TLoginWidget;
class TLoginDialog;
class TLoginManager;
class TProfile;
class TProfileBar;
class TProfileBox;
class TProfileView;
class TProfileWidget;
class TProfileDialog;
class TProfileManager;
class THeat;
class THeatBar;
class THeatBox;
class THeatView;
class THeatWidget;
class THeatDialog;
class THeatManager;
class TEmergency;
class TEmergencyBar;
class TEmergencyBox;
class TEmergencyView;
class TEmergencyWidget;
class TEmergencyDialog;
class TEmergencyManager;
class THealth;
class THealthDialog;
class THealthManager;
class THEVDialog;
class TInventoryDialog;
class TShieldDialog;
class TFirewallDialog;
class TSecurityDialog;
class TNetFilterDialog;
class TLanDialog;
class TPolicePrivacyDialog;
class TTermsUseDialog;
class TShareDialog;
class TWebBrowser;
class THTTP;
class THTTPClient;
class THTTPServer;
class TFTP;
class TFTPClient;
class TFTPServer;
class TSMTP;
class TSMTPClient;
class TSMTPServer;
class TPOP3;
class TPOP3Client;
class TPOP3Server;
class TNNTP;
class TNNTPClient;
class TNNTPServer;
class TSNTP;
class TSNTPClient;
class TSNTPServer;
class TWeather;
class TWeatherClient;
class TWeatherServer;
class TNews;
class TNewsClient;
class TNewsServer;
class TSMS;
class TSMSClient;
class TSMSServer;
class TMMS;
class TMMSClient;
class TMMSServer;
class TPNM;
class TPNMClient;
class TPNMServer;
class TRTSP;
class TRTSPClient;
class TRTSPServer;
class TRTMP;
class TRTMPClient;
class TRTMPServer;
class TTVP;
class TTVPClient;
class TTVPServer;
class TEngine;
class TEngineClient;
class TEngineServer;
class TEngineManager;
class TEngineDialog;
class TRenderDialog;
class TSwapDialog;
class TCacheDialog;
class TTempDialog;
class TNetTempDialog;
class TFileSystemDialog;
class TDeviceManager;
class TDeviceDialog;
class TThreadDialog;
class TTaskManager;
class TTaskDialog;
class TTaskWidget;
class TTask;
class TSwitch;
class TSwitchManager;
class TFriendDialog;
class TFriendsDialog;
class TShopDialog;
class TShoppingDialog;
class TBuyDialog;
class TSellDialog;
class TCommercialDialog;
class TGoogleDialog;
class TGoogle;
class TGoogleBar;
class TGoogleBox;
class TGoogleView;
class TGoogleWidget;
class TGoogleManager;
class TGoogleMap;
class TGoogleMapBar;
class TGoogleMapBox;
class TGoogleMapView;
class TGoogleMapWidget;
class TGoogleMail;
class TGoogleMailManager;
class TGoogleConnection;
class TFacebook;
class TFacebookManager;
class TOrkut;
class TOrkutManager;
class TGoogleBook;
class TGoogleBookManager;
class TGoogleStreetMap;
class TGoogleStreetMapManager;
class TGoogleStreetView;
class TGoogleStreetViewManager;
class TFlash;
class TFlashBox;
class TFlashWidget;
class TFlashControl;
class TApplet;
class TAppletControl;
class TAppletBox;
class TAppletManager;
class TAppletDialog;
class TFlashManager;
class TJava;
class TJavaManager;
class TJavaBox;
class TJavaControl;
class TJavaDialog;
class TJavaWidget;
class TKernel;
class TKernelDialog;
class TKernelManager;
class TSingleton;
class TANN;
class TANNBar;
class TANNBox;
class TANNWidget;
class TANNView;
class TANNDialog;
class TANNManager;
class TNeuro;
class TNeuroBar;
class TNeuroBox;
class TNeuroWidget;
class TNeuroView;
class TNeuroDialog;
class TNeuroManager;
class TStreetDialog;
class TCallDialog;
class TSetupDialog;
class TAboutBox;
class TPropertiesDialog;
class TOptionsDialog;
class TSkillDialog;
class TModDialog;
class TSocialNetwork;
class TLikesDialog;
class TFavoritesDialog;
class TBehavior;
class TBehaviorBar;
class TBehaviorBox;
class TBehaviorWidget;
class TBehaviorView;
class TBehaviorDialog;
class TBehaviorManager;
class TEducation;
class TEducationDialog;
class TEducationManager;
class TWellness;
class TWellnessDialog;
class TWellnessManager;
class TEnvironment;
class TEnvironmentDialog;
class TEnvironmentManager;
class TPersonal;
class TPersonalDialog;
class TPersonalManager;
class TSocial;
class TSocialDialog;
class TSocialManager;
class TCupid;
class TCupidDialog;
class TCupidManager;
class TFavoriteManager;
class TFriendsManager;
class TSocialNetworkManager;
class TCooperativeManager;
class TRelationship;
class TRelationshipDialog;
class TRelationshipManager;
class TEmotion;
class TEmotionDialog;
class TEmotionManager;
class TBusiness;
class TBusinessDialog;
class TBusinessManager;
class TVideo;
class TVideoDialog;
class TVideoManager;
class TDrink;
class TDrinkDialog;
class TDrinkManager;
class TFlirt;
class TFlirtDialog;
class TFlirtManager;
class TPorn;
class TPornDialog;
class TPornManager;
class TAdventure;
class TAdventureDialog;
class TAdventureManager;
class TMusic;
class TMusicDialog;
class TMusicManager;
class TEntertainment;
class TEntertainmentDialog;
class TEntertainmentManager;
class TCulture;
class TCultureDialog;
class TCultureManager;
class TFinance;
class TFinanceDialog;
class TFinanceManager;
class TPolice;
class TPoliceDialog;
class TPoliceManager;
class TGovernament;
class TGovernamentDialog;
class TGovernamentManager;
class TLaw;
class TLawDialog;
class TLawManager;
class TFamily;
class TFamilyDialog;
class TFamilyManager;
class TFamilyTree;
class TFamilyTreeBar;
class TFamilyTreeBox;
class TFamilyTreeView;
class TFamilyTreeWidget;
class TFamilyTreeDialog;
class TFamilyTreeComboBox;
class TBook;
class TBookDialog;
class TBookManager;
class TIdea;
class TIdeaDialog;
class TIdeaManager;
class TCity;
class TCityDialog;
class TCityManager;
class TSport;
class TSportDialog;
class TSportManager;
class TSportTheme;
class TSportThemeDialog;
class TSportThemeManager;
class TSportGame;
class TSportGameDialog;
class TSportGameManager;
class TSportGames;
class TSportGamesDialog;
class TSportGamesManager;
class TFootball;
class TFootballDialog;
class TFootballManager;
class TSoccer;
class TSoccerDialog;
class TSoccerManager;
class TVoleyball;
class TVoleyballDialog;
class TVoleyballManager;
class TGolf;
class TGolfDialog;
class TGolfManager;
class TSki;
class TSkiDialog;
class TSkiManager;
class TSurf;
class TSurfDialog;
class TSurfManager;
class TCarSpeed;
class TCarSpeedDialog;
class TCarSpeedManager;
class TSpeed;
class TSpeedDialog;
class TSpeedManager;
class TFlyBat;
class TFlyBatDialog;
class TFlyBatManager;
class TStockcar;
class TStockcarDialog;
class TStockcarManager;
class TCycleCross;
class TCycleCrossDialog;
class TCycleCrossManager;
class TMotocycleCross;
class TMotocycleCrossDialog;
class TMotocycleCrossManager;
class TF1;
class TF1Dialog;
class TF1Manager;
class TCasino;
class TCasinoDialog;
class TCasinoManager;
class TPoker;
class TPokerDialog;
class TPokerManager;
class TTwentyOne;
class TTwentyOneDialog;
class TTwentyOneManager;
class TChess;
class TChessDialog;
class TChessManager;
class TMathTrek;
class TMathTrekBar;
class TMathTrekBox;
class TMathTrekWidget;
class TMathTrekView;
class TMathTrekDialog;
class TMathTrekManager;
class TScience;
class TScienceDialog;
class TScienceManager;
class TTheme;
class TThemeDialog;
class TThemeManager;
class TTechnology;
class TTechnologyDialog;
class TTechnologyManager;
class TChild;
class TChildDialog;
class TChildManager;
class TMovie;
class TMovieBar;
class TMovieBox;
class TMovieView;
class TMovieWidget;
class TMovieDialog;
class TMovieManager;
class TCine;
class TCineBar;
class TCineBox;
class TCineView;
class TCineWidget;
class TCineDialog;
class TCineManager;
class TArt;
class TArtBar;
class TArtBox;
class TArtView;
class TArtWidget;
class TArtDialog;
class TArtManager;
class TDoodle;
class TDoodleBar;
class TDoodleBox;
class TDoodleView;
class TDoodleWidget;
class TDoodleDialog;
class TDoodleManager;
class TReader;
class TReaderBar;
class TReaderBox;
class TReaderView;
class TReaderWidget;
class TReaderDialog;
class TReaderManager;
class TWriter;
class TWriterBar;
class TWriterBox;
class TWriterView;
class TWriterWidget;
class TWriterDialog;
class TWriterManager;
class TTraffic;
class TTrafficBar;
class TTrafficBox;
class TTrafficView;
class TTrafficWidget;
class TTrafficDialog;
class TTrafficManager;
class TRoad;
class TRoadBar;
class TRoadBox;
class TRoadView;
class TRoadWidget;
class TRoadDialog;
class TRoadManager;
class TAir;
class TAirDialog;
class TAirManager;
class TTransport;
class TTransportDialog;
class TTransportManager;
class TBag;
class TBagDialog;
class TBagManager;
class TScan;
class TScanDialog;
class TScanManager;
class TCheck;
class TCheckDialog;
class TCheckManager;
class TEnemy;
class TEnemyDialog;
class TEnemyManager;
class TParental;
class TParentalDialog;
class TParentalManager;
class TPermission;
class TPermissionDialog;
class TPermissionManager;
class TFoodManager;
class TSleepManager;
class TNeedManager;
class TChangeManager;
class TBaseManager;
class TVictimManager;
class TCallManager;
class TTalkManager;
class TLiveManager;
class TSimManager;
class TRevManager;
class TFrequencyManager;
class TFrequency;
class TFrequencyDialog;
class TFrequencyWidget;
class TWorkManager;
class TSellManager;
class TBuyManager;
class TWorkDialog;
class TWork;
class TNews;
class TNewsManager;
class TNewsBar;
class TNewsLabel;
class TNewsBox;
class TNewsView;
class TNewsWidget;
class TNewsDialog;
class TMap;
class TMapManager;
class TMapBar;
class TMapLabel;
class TMapBox;
class TMapView;
class TMapWidget;
class TMapDialog;
class TCountry;
class TCountryManager;
class TCountryBar;
class TCountryLabel;
class TCountryBox;
class TCountryView;
class TCountryWidget;
class TCountryDialog;
class TState;
class TStateManager;
class TStateBar;
class TStateLabel;
class TStateBox;
class TStateView;
class TStateWidget;
class TStateDialog;
class TGeographic;
class TGeographicManager;
class TGeographicLabel;
class TGeographicBar;
class TGeographicBox;
class TGeographicView;
class TGeographicWidget;
class TGeographicDialog;
class TDeathmatchDialog;
class TStatsDialog;
class TStats;
class TStatsManager;
class TStatsWidget;
class TStatsLabel;
class TStatsBar;
class TStatsBox;
class TMath;
class TMathManager;
class TMathLabel;
class TMathBar;
class TMathBox;
class TMathView;
class TMathWidget;
class TMathDialog;
class TAftermath;
class TAftermathManager;
class TAftermathLabel;
class TAftermathBar;
class TAftermathBox;
class TAftermathView;
class TAftermathWidget;
class TAftermathDialog;
class TFallout;
class TFalloutManager;
class TFalloutBar;
class TFalloutBox;
class TFalloutView;
class TFalloutWidget;
class TFalloutDialog;
class TFail;
class TFailManager;
class TFailLabel;
class TFailBar;
class TFailBox;
class TFailView;
class TFailWidget;
class TFailDialog;
class TPlayer;
class TPlayerManager;
class TPlayerDialog;
class TPlayerWidget;
class TPlayerBox;
class TPlayerView;
class TEvent;
class TEventManager;
class TEventDialog;
class TEventWidget;
class TEventBox;
class TEventView;
class TNeedDialog;
class TNeedWidget;
class TSleepDialog;
class TSleepWidget;
class TEnergyWidget;
class TEnergyDialog;
class TEnergyManager;
class TRunDialog;
class TSpeech;
class TSpeechBar;
class TSpeechBox;
class TSpeechWidget;
class TSpeechDialog;
class TSpeechManager;
class TPalette;
class TPaletteBar;
class TPaletteBox;
class TPaletteWidget;
class TPaletteDialog;
class TPaletteView;
class TPaletteManager;
class TPaletteControl;
class TPattern;
class TPatternBar;
class TPatternBox;
class TPatternWidget;
class TPatternDialog;
class TPatternView;
class TPatternManager;
class TStoryboard;
class TStoryboardLevel;
class TStoryboardBar;
class TStoryboardBox;
class TStoryboardView;
class TStoryboardDialog;
class TStoryboardWidget;
class TStoryboardManager;
class TStoryboardControl;
class TStoryboardSystem;
class TScreenplay;
class TScreenplayLevel;
class TScreenplayBar;
class TScreenplayBox;
class TScreenplayView;
class TScreenplayDialog;
class TScreenplayWidget;
class TScreenplayManager;
class TScreenplayControl;
class TScreenplaySystem;
class TLoading;
class TLoadingBar;
class TLoadingBox;
class TLoadingWidget;
class TLoadingDialog;
class TLoadingView;
class TLoadingManager;
class TIntro;
class TIntroDialog;
class TIntroWidget;
class TIntroView;
class TIntroManager;
class TMedia;
class TMediaControl;
class TMediaBox;
class TMediaView;
class TMediaDialog;
class TMediaWidget;
class TMediaManager;
class TMediaControl;
class TMediaSystem;
class TTelevision;
class TTelevisionChannel;
class TTelevisionControl;
class TTelevisionRemoteControl;
class TTelevisionBox;
class TTelevisionView;
class TTelevisionDialog;
class TTelevisionWidget;
class TTelevisionManager;
class TTelevisionControl;
class TTelevisionSystem;
class TSong;
class TSongBar;
class TSongBox;
class TSongWidget;
class TSongDialog;
class TSongView;
class TSongManager;
class TWaveSpectrum;
class TWaveSpectrumControl;
class TWaveSpectrumBox;
class TWaveSpectrumBar;
class TWaveSpectrumWidget;
class TWaveSpectrumDialog;
class TWaveSpectrumManager;
class TSignal;
class TSignalLevel;
class TSignalBar;
class TSignalBox;
class TSignalWidget;
class TSignalDialog;
class TSignalManager;
class TGraph;
class TGraphBar;
class TGraphBox;
class TGraphDialog;
class TGraphWidget;
class TGraphView;
class TGraphManager;
class TChart;
class TChartBar;
class TChartBox;
class TChartDialog;
class TChartWidget;
class TChartView;
class TChartManager;
class TChartControl;
class TChart3D;
class TChart3DBar;
class TChart3DBox;
class TChart3DDialog;
class TChart3DWidget;
class TChart3DView;
class TChart3DManager;
class TChart3DControl;
class THelper;
class THelperLevel;
class THelperBar;
class THelperBox;
class THelperView;
class THelperDialog;
class THelperWidget;
class THelperManager;
class THelperControl;
class THelperSystem;
class THelp;
class THelpLevel;
class THelpBar;
class THelpBox;
class THelpView;
class THelpDialog;
class THelpWidget;
class THelpManager;
class THelpControl;
class THelpSystem;
class TAvatar;
class TAvatarBar;
class TAvatarBox;
class TAvatarView;
class TAvatarWidget;
class TAvatarDialog;
class TAvatarManager;
class TAvatarSetup;
class TAvatarSetupManager;
class TAvatarSetupDialog;
class TBioSystem;
class TBioSystemManager;
class TBioSystemSetup;
class TBioSystemDialog;
class TDNA;
class TDNAManager;
class TDNASetup;
class TDNADialog;
class TInitSetupDialog;
class TInitDialog;
class TWizardDialog;
class TVictoryDialog;
class TVictory;
class TVictoryBar;
class TVictoryBox;
class TVictoryManager;
class TVictoryDialog;
class TVictoryWidget;
class TVictoryView;
class TWeapon;
class TWeaponBar;
class TWeaponBox;
class TWeaponManager;
class TWeaponDialog;
class TWeaponWidget;
class TWeaponView;
class TLevel;
class TLevelBar;
class TLevelBox;
class TLevelView;
class TLevelWidget;
class TLevelDialog;
class TLevelManager;
class TEpisode;
class TEpisodeBar;
class TEpisodeBox;
class TEpisodeView;
class TEpisodeWidget;
class TEpisodeDialog;
class TEpisodeManager;
class TChapter;
class TChapterBar;
class TChapterBox;
class TChapterView;
class TChapterWidget;
class TChapterDialog;
class TChapterManager;
class TLoadGame;
class TSaveGame;
class TLoadGameDialog;
class TSaveGameDialog;
class TLoadGameManager;
class TSaveGameManager;
class TGameFileView;
class TGameFileBar;
class TGameFileBox;
class TGameFileControl;
class TGameFileImage;
class TGameFileImageList;
class TGameFilePreview;
class THeaderSection;
class TSection;
class TSectionBar;
class TSectionBox;
class TSectionView;
class TSectionWidget;
class TSectionDialog;
class TSectionManager;
class TSession;
class TSessionManager;
class TSessionDialog;
class TAccount;
class TAccountBar;
class TAccountBox;
class TAccountView;
class TAccountDialog;
class TAccountWidget;
class TAccountManager;
class TAccountControl;
class TRadio;
class TRadioManager;
class TRadioDialog;
class TRadioBar;
class TRadioBox;
class TRadioWidget;
class TRadioView;
class TWanted;
class TWantedLevel;
class TWantedBar;
class TWantedBox;
class TWantedView;
class TWantedDialog;
class TWantedWidget;
class TWantedManager;
class TWantedControl;
class TWantedSystem;


typedef void (* TNotifyEvent)(TControl* sender);
typedef void (* TTimerEvent)(TComponent* sender);
typedef void (* TKeyEvent)(TControl* sender,int key);
typedef void (* TMouseEvent)(TControl* sender, int button, int x, int y);
typedef void (* TMouseMoveEvent)(TControl* sender, int x, int y);
typedef void (* TWinRenderEvent)(TWinControl* sender);
typedef void (* TRenderEvent)(TControl* sender);
typedef void (* TRenderComponentEvent)(TComponent* sender);


// typedef void (* TFEGUI_NotifyEvent)(int sender);
typedef void (* TFEGUI_NotifyEvent)(TControl* sender);
typedef void (* TFEGUI_RenderEvent)(TControl* sender);


#pragma option push -b-
enum TBrushStyle { bsSolid, bsClear, bsHorizontal, bsVertical, bsFDiagonal, bsBDiagonal, bsCross, bsDiagCross };
#pragma option pop

#pragma option push -b-
enum TPenStyle { psSolid, psDash, psDot, psDashDot, psDashDotDot, psClear, psInsideFrame };
#pragma option pop

#pragma option push -b-
enum TPenMode { pmBlack, pmWhite, pmNop, pmNot, pmCopy, pmNotCopy, pmMergePenNot, pmMaskPenNot, pmMergeNotPen, pmMaskNotPen, pmMerge, pmNotMerge, pmMask, pmNotMask, pmXor, pmNotXor };
#pragma option pop

#pragma option push -b-
enum TShapeType { stRectangle, stSquare, stRoundRect, stRoundSquare, stEllipse, stCircle };
#pragma option pop

#pragma option push -b-
enum TComboBoxStyle { csDropDown, csDropDownList, csOwnerDrawFixed, csOwnerDrawVariable, csSimple };
#pragma option pop

#pragma option push -b-
enum TIconArrangement { iaTop, iaLeft };
#pragma option pop

#pragma option push -b-
enum TViewStyle { vsIcon, vsSmallIcon, vsList, vsReport };
#pragma option pop

#pragma option push -b-
enum TListHotTrackStyle { htHandPoint, htUnderlineCold, htUnderlineHot };
#pragma option pop

#pragma option push -b-
enum TSortType { stNone, stData, stText, stBoth };
#pragma option pop

#pragma option push -b-
enum TTrackBarOrientation { trHorizontal, trVertical };
#pragma option pop

#pragma option push -b-
enum TUDOrientation { udHorizontal, udVertical };
#pragma option pop

#pragma option push -b-
enum TScrollKind { sbHorizontal, sbVertical };
#pragma option pop

#pragma option push -b-
enum TTextLayout { tlTop, tlCenter, tlBottom };
#pragma option pop

#pragma option push -b-
enum TProgressBarOrientation { pbHorizontal, pbVertical };
#pragma option pop

#pragma option push -b-
enum TWindowState { wsNormal, wsMinimized, wsMaximized };
#pragma option pop

#pragma option push -b-
enum TFormStyle { fsNormal, fsMDIChild, fsMDIForm, fsStayOnTop };
#pragma option pop

#pragma option push -b-
enum TBorderIcon { biSystemMenu, biMinimize, biMaximize, biStayOnTop, biRollUp, biHelp };
#pragma option pop
/*
typedef FILE* (FEGUI_CALLBACK *FEGUI_FILE_OPENCALLBACK) (const char* filename, const char* mode);
typedef int (FEGUI_CALLBACK *FEGUI_FILE_CLOSECALLBACK) (FILE* stream);
typedef long (FEGUI_CALLBACK *FEGUI_FILE_TELLCALLBACK) (FILE* stream);
typedef int (FEGUI_CALLBACK *FEGUI_FILE_SEEKCALLBACK) (FILE* stream, long offset, int whence);
typedef size_t (FEGUI_CALLBACK *FEGUI_FILE_READCALLBACK) (void* ptr, size_t size, size_t n, FILE* stream);
typedef size_t (FEGUI_CALLBACK *FEGUI_FILE_WRITECALLBACK) (const void* ptr, size_t size, size_t n, FILE* stream);
*/
typedef struct
{
unsigned int textureid;
unsigned char* data;
} bitmapfontchar_t;

typedef struct
{
char ptr[4];
int fmt;
int ver;
int tex;
int fw;
int fh;
int dw;
int dh;
int numchars;
bitmapfontchar_t chars[256];
} bitmapfont_t;




#endif // CTYPES_H
